AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  patientcheckout

  Sample SAM Template for patientcheckout


Globals:
  Function:
    Timeout: 20

Resources:
  PatientCheckoutBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-${AWS::AccountId}-${AWS::Region}
  PatientCheckoutTopic:
    Type: AWS::SNS::Topic
  PatientCheckoutFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: patientcheckout
      Handler: com.thanthu.aws.lambda.s3sns.PatientCheckoutLambda::handler
      Runtime: java11
      MemorySize: 512
      Policies:
        - S3ReadPolicy:
            BucketName: !Sub ${AWS::StackName}-${AWS::AccountId}-${AWS::Region}
      Environment: 
        Variables:
          PATIENT_CHECKOUT_TOPIC: !Ref PatientCheckoutTopic
      Events:
        S3Event:
          Type: S3 
          Properties:
            Bucket: !Ref PatientCheckoutBucket
            Events: s3:ObjectCreated:*